# Define the Docker Compose version
version: "3"

# Define the services that make up your application
services:

    # Configuration for the php service
    php:
        container_name: ${PROJECT_NAME}-php
        image: ${PROJECT_NAME}-php:${PROJECT_NAME}-${PROJECT_VERSION}
        build:
            context: .
            dockerfile: ${PHP_DOCKERFILE}Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./Php:/var/Php
        depends_on:
            - mariadb
        networks:
            - laravel
        environment:
            DB_CONNECTION: ${MARIADB_CONNECTION}
            DB_HOST: ${MARIADB_HOST}
            DB_PORT: ${MARIADB_PORT}
            DB_DATABASE: ${MARIADB_DATABASE}
            DB_USERNAME: ${MARIADB_USERNAME}
            DB_PASSWORD: ${MARIADB_PASSWORD}
        working_dir: /var/Php
        command: sh -c '[ -z "$(ls -A /var/Php)" ] && tail -F /dev/null || php artisan serve --host 0.0.0.0 --port 8000'

    # Configuration for the database service
    mariadb:
        container_name: ${PROJECT_NAME}-mariadb
        image: ${PROJECT_NAME}-mariadb:${PROJECT_NAME}-${PROJECT_VERSION}
        build:
            context: .
            dockerfile: ${MARIADB_DOCKERFILE}Dockerfile
        tty: true
        environment:
            MYSQL_DATABASE: ${MARIADB_DATABASE}
            MYSQL_USER: ${MARIADB_USERNAME}
            MYSQL_PASSWORD: ${MARIADB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - database:/var/lib/mysql
        networks:
            - laravel

    # Configuration for the phpMyAdmin service            
    phpmyadmin:
        container_name: ${PROJECT_NAME}-phpmyadmin
        image: ${PROJECT_NAME}-phpmyadmin:${PROJECT_NAME}-${PROJECT_VERSION}
        build:
            context: .
            dockerfile: ${PHPMYADMIN_DOCKERFILE}/Dockerfile
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mariadb
            PMA_USER: ${MARIADB_USERNAME}
            PMA_PASSWORD: ${MARIADB_PASSWORD}
        depends_on:
            - mariadb
        networks:
            - laravel

# Define the Project's Network
networks:
    laravel:
        driver: bridge

# Define the Project's Volumes
volumes:
    database:
        driver: local
